const express=require('express');const http=require('http');const cors=require('cors');const crypto=require('crypto');const {Server}=require('socket.io');
const PUZZLES=require('./puzzles.json');
const app=express();app.use(cors({origin:true}));app.use(express.json());const server=http.createServer(app);const io=new Server(server,{cors:{origin:'*',methods:['GET','POST']}});
const rooms=new Map(),queue=[];
const code=()=>{let c;do c=String(100000+crypto.randomInt(900000));while(rooms.has(c));return c};
const seeded=(seed)=>{let x=(seed>>>0)||1;return()=>{x=(Math.imul(1664525,x)+1013904223)>>>0;return x/4294967296}};
const perm=(n,rng)=>{const a=Array.from({length:n},(_,i)=>i);for(let i=n-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const transformSudoku=(item,seed)=>{const rng=seeded(seed);const bands=perm(3,rng);const rows=[];bands.forEach(b=>perm(3,rng).forEach(r=>rows.push(b*3+r)));const stacks=perm(3,rng);const cols=[];stacks.forEach(st=>perm(3,rng).forEach(c=>cols.push(st*3+c)));const digits=perm(9,rng).map(x=>x+1);const mapGrid=g=>rows.map(r=>cols.map(c=>{const v=g[r][c];return v?digits[v-1]:0}));return{puzzle:mapGrid(item.puzzle),solution:mapGrid(item.solution)}};
const validCode=v=>/^\d{6}$/.test(String(v));
const pub=r=>r.players.map(({id,name,score})=>({id,name,score}));
function newRoom(host){const c=code();const r={code:c,difficulty:'Easy',started:false,players:[{id:host.id,name:host.name,score:0}],boards:new Map(),puzzle:null,solution:null};rooms.set(c,r);return r}
function start(r,difficulty){const l=PUZZLES[difficulty]||PUZZLES.Easy;const idx=Date.now()%5000;const base=l[idx%l.length];const p=transformSudoku(base,((Object.keys(PUZZLES).indexOf(difficulty)+1)*1000003+idx*9176+17)>>>0);r.difficulty=difficulty;r.puzzle=p.puzzle;r.solution=p.solution;r.started=true;r.boards=new Map(r.players.map(x=>[x.id,r.puzzle.map(row=>row.map(v=>v))]));io.to(r.code).emit('game:started',{difficulty:r.difficulty,puzzle:r.puzzle,startedAt:Date.now()})}
function valid(r,row,col,value){return Number.isInteger(row)&&row>=0&&row<9&&Number.isInteger(col)&&col>=0&&col<9&&Number.isInteger(value)&&value>=1&&value<=9&&r.puzzle[row][col]===0&&r.solution[row][col]===value}
function solved(r,b){for(let i=0;i<9;i++)for(let j=0;j<9;j++)if(b[i][j]!==r.solution[i][j])return false;return true}
app.get('/health',(_,res)=>res.json({ok:true,service:'sudoku-friends',version:'2.0.4'}));
app.get('/',(_,res)=>res.json({service:'Sudoku Friends backend',status:'online',version:'2.0.4'}));
io.on('connection',socket=>{
 socket.on('room:create',(p={})=>{const r=newRoom({id:socket.id,name:String(p.name||'Player').slice(0,20)});socket.join(r.code);socket.data.roomCode=r.code;socket.emit('room:created',{code:r.code,players:pub(r)})});
 socket.on('room:join',(p={})=>{const requested=String(p.code||p.roomId||'');if(!validCode(requested))return socket.emit('room:error',{message:'Room code must be exactly 6 digits'});const r=rooms.get(requested);if(!r)return socket.emit('room:error',{message:'Room not found'});if(r.started)return socket.emit('room:error',{message:'Match already started'});if(r.players.length>=2)return socket.emit('room:error',{message:'Room is full'});r.players.push({id:socket.id,name:String(p.name||'Player').slice(0,20),score:0});socket.join(r.code);socket.data.roomCode=r.code;io.to(r.code).emit('room:ready',{code:r.code,players:pub(r)})});
 socket.on('match:queue',(p={})=>{const difficulty=PUZZLES[p.difficulty]?p.difficulty:'Easy';queue.push({id:socket.id,name:String(p.name||'Player').slice(0,20),difficulty});if(queue.length>=2){const a=queue.shift(),b=queue.shift();const r=newRoom(a);r.players.push({id:b.id,name:b.name,score:0});for(const x of [a,b]){const s=io.sockets.sockets.get(x.id);s?.join(r.code);if(s)s.data.roomCode=r.code}io.to(r.code).emit('match:found',{code:r.code,players:pub(r)});start(r,r.difficulty)}});
 socket.on('game:start',(p={})=>{const r=rooms.get(socket.data.roomCode);if(!r||r.players.length!==2||r.started)return;start(r,PUZZLES[p.difficulty]?p.difficulty:r.difficulty||'Easy')});
 socket.on('game:move',(p={})=>{const r=rooms.get(socket.data.roomCode);if(!r||!r.started)return;const b=r.boards.get(socket.id);const row=Number(p.row),col=Number(p.col),value=Number(p.value);if(!b||!valid(r,row,col,value)||b[row][col]!==0)return socket.emit('game:mistake',{row,col});b[row][col]=value;io.to(r.code).emit('game:move',{row,col,value,playerId:socket.id});if(solved(r,b)){r.started=false;const pl=r.players.find(x=>x.id===socket.id);if(pl)pl.score++;io.to(r.code).emit('game:winner',{playerId:socket.id,name:pl?.name||'Player'})}});
 socket.on('game:reaction',p=>{const r=rooms.get(socket.data.roomCode);if(r)io.to(r.code).emit('game:reaction',{playerId:socket.id,text:String(p?.text||'🔥').slice(0,30)})});
 socket.on('disconnect',()=>{const qi=queue.findIndex(x=>x.id===socket.id);if(qi>=0)queue.splice(qi,1);const r=rooms.get(socket.data.roomCode);if(!r)return;r.players=r.players.filter(x=>x.id!==socket.id);r.boards.delete(socket.id);io.to(r.code).emit('room:player-left');if(!r.players.length)rooms.delete(r.code)})
});
server.listen(Number(process.env.PORT)||3000,()=>console.log('Sudoku Friends backend 2.0.4 listening'));
